# Generated by Django 6.1.1 on 2026-09-22 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrescue_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptablePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Other', 'Other')], db_index=True, max_length=20)),
                ('breed', models.CharField(db_index=True, max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Age in years or months')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('health_status', models.CharField(default='Vaccinated, De-wormed & Healthy', max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='adoption_photos/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for Adoption'), ('PENDING_ADOPTION', 'Pending Adoption Review'), ('ADOPTED', 'Adopted'), ('INACTIVE', 'Inactive / Withdrawn')], db_index=True, default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptable_pets_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(choices=[('Own House', 'Own House'), ('Rented Apartment', 'Rented Apartment'), ('Farm / Villa', 'Farm / Villa'), ('Other', 'Other')], default='Own House', max_length=50)),
                ('experience', models.TextField(help_text='Previous pet experience')),
                ('reason', models.TextField(help_text='Reason for adoption')),
                ('contact', models.CharField(help_text='Contact phone number or preferred contact method', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Reviewer notes from adoption portal admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adoptable_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='petrescue_app.adoptablepet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
